### ISSUE TITLE
SshCredential extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#10]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript") 

SshCredential

## Brief description of functionality to be provided 

Define credentials for a remote host accepting SSH connections. The extension does not actually do anything, but may be useful as reference.

## Issue Dependencies

If there are any other issues that should be implemented first, list them here

* `CliInputPrompt` (already implemented)
* `AwsBoto3GetSecret` (not defined yet)

# More detailed functional requirements

Use something like [paramiko](https://www.paramiko.org/) for SSH functionality.

The resulting client (or other objects) will be stored in appropriate variables like `<<name>>:client` 

Proposed spec:

```yaml
spec:
  type: string # Either ssh-private-key or ssh-credentials
  sshPrivateKey: # only used when type==ssh-private-key  
    localFilePath: string # Path to the private key
  sshCredentials: # only used when type==ssh-credentials
    username: string
    password: string # Never put the actual password. See https://github.com/nicc777/py-animus/blob/main/doc/placeholder_values.md and https://github.com/nicc777/py-animus/blob/main/doc/placeholder_values.md#variables-and-manifest-dependencies
```

This extension sets the following variables, depending on context (default value is `None` for variables not in scope):

* `SSH_PRIVATE_KEY_FILE` - Path to the private key
* `SSH_USERNAME` - The username
* `SSH_PASSWORD` - The resolved password
