### ISSUE TITLE
HttpBasicCredential extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#11]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript") 

HttpBasicCredential

## Brief description of functionality to be provided 

Provides a username and password for HTTP Basic Authentication

## Issue Dependencies

If there are any other issues that should be implemented first, list them here

* `CliInputPrompt`
* `AwsBoto3GetSecret`

# More detailed functional requirements

Proposed spec:

```yaml
spec:
  username: string
  passwordSrcReference: string # Contains the name of the manifest that will provide the password, for example using "AwsBoto3GetSecret" or "CliInputPrompt"
  passwordVariableName: string # Contains the variable name, depending on source manifest implementation, that will contain the password
 
```
