### ISSUE TITLE
AwsBoto3GetSecret extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#12]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript") 

AwsBoto3GetSecret

## Brief description of functionality to be provided 

Retrieves the secret value stored in AWS Secret Manager

## Issue Dependencies

If there are any other issues that should be implemented first, list them here

* #3 

# More detailed functional requirements

Retrieves a secret and stores the value in a variable for use by other manifests

The spec will allow custom Python code to be added for post-secret retrieval processing as may be required for dependent manifests that uses the secret value, for example when only a single value in a complex JSON object is required.

Proposed spec:

```yaml
spec:
  secretName: string # Required
  awsBoto3SessionReference: string # Required - the AWS credentials to use for this secret
  conversionTarget: string # Optional, default=None. Other options: "dict" (assumes the original value is a JSON string).
```

The following variable will be set once the secret is retrieved:

* `VALUE` - contains the secret value
* `TYPE` - Either "string" or "binary"

References:

* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager.html
* https://boto3.amazonaws.com/v1/documentation/api/latest/guide/secrets-manager.html
