### ISSUE TITLE
GitRepoResource extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#13]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript") 

GitRepoResource

## Brief description of functionality to be provided 

Points to a file (or files) or directory within a `GitRepo`

## Issue Dependencies

If there are any other issues that should be implemented first, list them here

* #9 

# More detailed functional requirements

Proposed spec:

```yaml
spec:
  gitRepoReference: string # POints to a "GitRepo"
  branch: string # Optional, default is the default None (use value of "GitRepo")
  resources: # at least one file or one directory must be specified
    files:
    - string
    - string
    directories:
    - string
    - string
  targetDir: string # The selected files and directories will be copied (recursively) to this directory. If the directory does not exist, it will be created
  variableFilesIncludeDirectoryContents: false # Optional, default false. When creating the files variable, and this is true, recursively dive into the selected directories and add all their files as well.
```

Creates two variables:

* `<<name>>:files` containing a list of files (can be zero length) - absolute path in `targetDir`. Includes all files in selected directories as well when `variableFilesIncludeDirectoryContents` is true
* `<<name>>:directories` containing a list of directories (can be zero length) - absolute path in `targetDir`
