### ISSUE TITLE
AwsBoto3CloudFormationTemplateTags extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#14]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript") 

AwsBoto3CloudFormationTemplateTags

## Brief description of functionality to be provided 

Defines tags to be attached to one or more `AwsBoto3CloudFormationTemplate` manifests

## Issue Dependencies

If there are any other issues that should be implemented first, list them here

* None

# More detailed functional requirements

Proposed spec:

```yaml
spec:
  tags:
  - tagName: string # Required
    tagValue: string # Required, cannot be empty
```

Then later, in #4 (actual template), the tags can be referenced by the name of `AwsBoto3CloudFormationTemplateTags` manifest:

```yaml
spec:
  tagReferences: # optional - reference one or more "AwsBoto3CloudFormationTemplateTags" manifests
  - string # Reference to the name of a "AwsBoto3CloudFormationTemplateTags" manifest
```

The data will be stored in the following `Variable` objects:

* `TAG_KEYS` - A list of keys
* `TAGS` - A dictionary in the format `{ "<<tag_key>>": "<<tag_value>>" }`. All `tag_value` values will be strings
