### ISSUE TITLE
AwsBoto3S3Bucket extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#15]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript") 

AwsBoto3S3Bucket

## Brief description of functionality to be provided 

Ensures an S3 bucket exists

## Issue Dependencies

If there are any other issues that should be implemented first, list them here

* #3 

# More detailed functional requirements

Proposed spec:

```yaml
spec:
  awsBoto3Session: string # string, required, name of a "AwsBoto3Session" manifest to use for the session
  name: string # string, required
  acl: string # string, optional, default=private, when supplied must be one of "private" or "public-read" or "public-read-write" or "authenticated-read"
  grantFullControl: string # string, optional, default=None maps to "GrantFullControl"
  grantRead: string # string, optional, default=None maps to "GrantRead"
  grantReadACP: string # string, optional, default=None maps to "GrantReadACP"
  grantWrite: string # string, optional, default=None maps to "GrantWrite"
  grantWriteACP: string # string, optional, default=None maps to "GrantWriteACP"
  objectLockEnabledForBucket: false # boolean, optional, default=false, maps to "ObjectLockEnabledForBucket"
  objectOwnership: string # string, optional, default="BucketOwnerPreferred", maps to "ObjectOwnership"
```
