### ISSUE TITLE
AwsBoto3S3Files extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#22]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript") 

AwsBoto3S3Files

## Brief description of functionality to be provided 

Synchronize a local directory or files to a AWS S3 bucket created by `AwsBoto3S3Bucket`. 

The intention is more for uploading critical artifacts needed in deployment of infrastructure, like CloudFormation templates, scripts etc. For large bulk uploads, the AWS CLI is still better by running [aws s3 sync](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html).

This solution is more for a smaller number of files - couple of thousand at the most, but even better for less than 1000 files, especially if checksum validation of each file is required.

## Issue Dependencies

If there are any other issues that should be implemented first, list them here

* #3  - AwsBoto3Session
* #15 - AwsBoto3S3Bucket

# More detailed functional requirements

Variables to set:

* `:SYNC_RESULT` - Set to value `ALL_OK`  when done.

Basic Process:

* Get the current file listing in the S3 bucket
* List local files & directories and build a destination map for each file
* Compare the map against the current S3 files
    * If `verifyChecksums` is true for a particular file, download remote, calculate checksum and compare to local file checksum
    *  Build a transfer queue list based on all evaluations
* Start the transfers.
    * On failures, take into account the `onError` setting
    * If a log file was specified, create file transfer log entries.
* For any additional files on S3 not found locally: if `actionExtraFilesOnS3` is set to `delete`, delete the extra files on S3 (default is to keep them)
* Set `:SYNC_RESULT`

Each uploaded file will be tagged ([example](https://stackoverflow.com/questions/55592349/how-to-upload-to-aws-s3-with-object-tagging)) with the keys:

*  `AnimusEnvironment` - With the environment used to create this file
* `AnimusManifestName` - The name of the manifest that uploaded this file
* `AnimusUploadTimestamp` - The Unix timestamp when the action was performed (relative to the Manifest being applied)
* `AnimusFileChecksum` - The file checksum

Proposed spec:

```yaml
---
kind: AwsBoto3Session
version: v1
metadata:
  name: aws-boto3-session-v1-minimal
  skipApplyAll: true
  skipDeleteAll: true
spec:
  awsRegion: us-east-1
  profileName: my-profile
---
kind: AwsBoto3S3Bucket
version: v1
metadata:
  name: aws-boto3-s3-bucket-v1-minimal
  dependencies:
    apply:
    - aws-boto3-session-v1-minimal
    delete:
    - aws-boto3-session-v1-minimal
  executeOnlyOnceOnApply: true
spec:
  awsBoto3Session: aws-boto3-session-v1-minimal
  name: my-very-unique-bucket-name
---
kind: AwsBoto3S3Files
version: v1
metadata:
  name: aws-s3-files
  dependencies:
    apply:
    - aws-boto3-session-v1-minimal
    - aws-boto3-s3-bucket-v1-minimal # Because we need to ensure the S3 bucket exists first
    delete:
    - aws-boto3-session-v1-minimal # Just delete all the files if the exist on S3
spec:
  awsBoto3Session: aws-boto3-session-v1-minimal
  s3Bucket: aws-boto3-s3-bucket-v1-minimal # Name of the AwsBoto3S3Bucket manifest to use as reference bucket for the files
  destinationDirectory: /example
  localStagingDirectory: /tmp/staging # If not set, a tmp directory will be calculated and created. Used only when checksums must be verified (this is where the downloaded files go)
  transferLogFile: /tmp/log/file_transfer.log # Optional. Apart from the normal logging, log specific file transfer transactions to this file. If not set, no additional transfer log will be created. If the file exist, new transfers will be appended.
  sources:
  - sourceType: localFiles
    baseDirectory: /tmp/some-dir-1
    verifyChecksums: true # If set to true, very expensive! Downloads each file first to calculate the chacksum
    files:
    - file1.txt
    - file2.txt
  - sourceType: localDirectories
    recurse: true
    baseDirectory: /tmp/some-dir-2
    verifyChecksums: false
    directories:
    - sub-dir1/dir1
    - sub-dir2/dir2
  ifFileExists:
    overWrite: true # Overwrite the current version
  onError: warn # Or "exception" to stop further processing
  actionExtraFilesOnS3: keep # or "delete" (default="keep") - what to do with files on S3 not present locally (by matching file path and remote key)
```
