### ISSUE TITLE
WriteFile extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#31]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript")

`WriteFile`

## Brief description of functionality to be provided

Write data to file - typicall from a `Value` or a `Variable`

## Issue Dependencies

If there are any other issues that should be implemented first, list them here

* None

# More detailed functional requirements

Example spec:

```yaml
spec:
  targetFile: string # Full path to a file
  data: string # The actual content of the file. Typicall a Value or Variable reference will be used here
  actionIfFileAlreadyExists: string # optional (default=overwrite). Allowed values: overwrite (write the data to the file anyway - overwriting any previous data), skip (leave the current file as is and skip)
  fileMode: string # optional (default=normal). Allowed values: normal (chmod 600) or executable (chmod 700)
```

Variables to be set:

* `FILE_PATH` - The full path to the file.
* `WRITTEN` - Boolean. If the file previously existed and the `actionIfFileAlreadyExists` is `skip`, then this value will be False
* `EXECUTABLE` - Boolean True if the file can be executed (default is False)
* `SIZE` - The size in bytes of the file after all processing
* `SHA256_CHECKSUM` - The checksum of the file after all processing

`fileMode` is processed at the end, regardless if the file previously existed or not.

If `data` is null, an empty file will be created.
