### ISSUE TITLE
AwsBoto3CloudFormationTemplate extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#4]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript") 

AwsBoto3CloudFormationTemplate

## Brief description of functionality to be provided 

When called with "apply" does one of two actions (default):

1. If the template has not been applied before, apply the new template
2. If the template was applied before, create and apply a change set

The behavior can be fine tuned with the `spec.changeDetection` settings

## Issue Dependencies

* #3 

Optional dependencies:

* #14 
* #6 

# More detailed functional requirements

References:

* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-describing-stacks.html

Proposed Spec:

```yaml
spec:
  awsBoto3SessionReference: string # The AWS credentials to use for this template. The value is the "name" of the relevant "AwsBoto3Session" manifest to use
  tagReferences: # optional
  - string # Reference to the name of a "AwsBoto3CloudFormationTemplateTags" manifest
  parameterReferences: # optional
  - string # Reference to the name of a "AwsBoto3CloudFormationTemplateParameters" manifest
  templatePath: string # Path to the CloudFormation file. The file must be on the local filesystem. If the file is in a Git repository, first use "GitRepo" to get the files onto the local system (as an example)
  options: # CloudFormation specific options
    disableRollback: false # Boolean, optional, default false (maps to "DisableRollback" option)
    timeoutInMinutes: 600 # integer, optional, default 600 (maps to "TimeoutInMinutes" option)
    notificationARNs: [] # list of strings, optional, default [] (maps to "NotificationARNs" option)
    capabilities: [] # list of string, optional, default None (maps to "Capabilities") - if supplied, can be "CAPABILITY_IAM" and/or "CAPABILITY_NAMED_IAM" and/or "CAPABILITY_AUTO_EXPAND"
    onFailure: string # string, optional, default "ROLLBACK". If supplied, one of "DO_NOTHING" or "ROLLBACK" or "DELETE"
    enableTerminationProtection: false # boolean, optional, default false  (maps to "EnableTerminationProtection" option)
  changeDetection: # Optional
    features:
      remoteTemplateValueEvaluation: boolean # (Default=True) See https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation/client/get_template.html - the remote template will be compared with the current one.
      alwaysCreateChangeset: boolean # (Default=False), regardless if changes are present or not, create a changeset. This makes other change evaluation more or less redundant.
    customEvaluations: # By default there are no custom evaluation. A custom evaluation is based on a variable from another manifest (which should be dependencies)
      variableEvaluations:
      - variableName: string # The name of the "Variable". 
        expectedValue: string # The Python string representation of a variable value
        changeDetectedIfValueMatch: boolean # Optional (Default=True). If the "expectedValue" is matched, assume changes were detected. If "False" and value OTHER than the "expectedValue" will indicate change was detected.
  raiseExceptionOnFinalStatusValues: # Optional (Default="CREATE_FAILED", "DELETE_FAILED", "ROLLBACK_FAILED", "UPDATE_FAILED", "UPDATE_ROLLBACK_FAILED", "IMPORT_ROLLBACK_FAILED"). Add one or more of the following status codes that will force an exception to be raised (causing further deployment processing to stop): "CREATE_COMPLETE", "CREATE_FAILED", "DELETE_COMPLETE", "DELETE_FAILED", "ROLLBACK_COMPLETE", "ROLLBACK_FAILED", "UPDATE_COMPLETE", "UPDATE_FAILED", "UPDATE_ROLLBACK_COMPLETE", "UPDATE_ROLLBACK_FAILED", "IMPORT_COMPLETE", "IMPORT_ROLLBACK_FAILED", "IMPORT_ROLLBACK_COMPLETE". An empty list will ignore any status
  - string
  variableMappings:
    outputs:
    - outputKey: string # The value of the output key. The same as the CloudFormation output "Logical ID" for example "InstanceID"
      variableName: string # A name to use for the Variable, for example "INSTANCE_ID"
    resources:
    - logicalResourceId: string # The value of the output key. The same as the CloudFormation output "Logical ID" for example "InstanceID"
      variables: # At least one of the following must be set. 
      - physicalResourceId: string # Variable name for storing the "PhysicalResourceId"
        resourceType: string # Variable name for storing the "ResourceType"
        resourceStatus: string # Variable name for storing the "ResourceStatus"
```

Variables to be set:

* `FINAL_STATUS` - string with the final CLoudFormation status
* `LOCAL_TEMPLATE_CHECKSUM` - string with the SHA256 checksum of the template in the local file (processed template - not the file checksum)
* `REMOTE_TEMPLATE_CHECKSUM` - string with the SHA256 checksum of the remote template (processed template - not the raw string checksum)
* And any additional mappings as defined in `spec.variableMappings`

The following CloudFormation status codes is assumed to indicate that the stack deployment is complete:

* `CREATE_COMPLETE`
* `CREATE_FAILED`
* `DELETE_COMPLETE`
* `DELETE_FAILED`
* `ROLLBACK_COMPLETE`
* `ROLLBACK_FAILED`
* `UPDATE_COMPLETE`
* `UPDATE_FAILED`
* `UPDATE_ROLLBACK_COMPLETE`
* `UPDATE_ROLLBACK_FAILED`
* `IMPORT_ROLLBACK_FAILED`
* `IMPORT_ROLLBACK_COMPLETE`
