### ISSUE TITLE
PythonFunction extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#40]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript")

`PythonFunction`

## Brief description of functionality to be provided

Execute a python function

## Issue Dependencies

If there are any other issues that should be implemented first, list them here

* None

# More detailed functional requirements

Proposed Spec:

```yaml
spec:
  requirements: # Additional requirements to be installed by pip in a venv for this function. By default `boto3` will already be installed together with all the other standard Python libraries (default is empty list)
  - string
  imports: # List of strings representing the import statements. List all that is required (default is empty list)
  - string
  type: string # Optional (default="file"). Either "file" or "inlineCode".
  value: string # Required. If `type` is "file", the path to the python file to execute. If `type` is "inlineCode", the actual python code to execute
  parametersToInclude: # Optional. Imports will automatically be adjusted for this.
  - variables: boolean # Default=True - include the `VariableCache`.  Parameter name will be `variables`
  - targetEnvironment: boolean # Default=True.  Parameter name will be `target_environment`
  additionalParameters: # Optional. Default is an empty list
  - name: string # The name of the parameter
    value: object # Some valid object. Can be a reference to a `Variable` or `Value`
  stopProcessingOnException: boolean # Optional (default=True). When an exception is raised, stop further processing if this value is True.
```

The function signature: 

```python
def animus_function(class_name: str, manifest_name: str, logger, **kwargs):
  pass # Your code here... "variables" and "target_environment" will be in kwargs
```

No return value is expected. Instead, include the parameter `variables` and set the variable using this code:

```python
variable_name = '{}:{}:{}:MY_VARIABLE_NAME'.format(class_name, manifest_name, target_environment)
variable_cache.store_variable(
    variable=Variable(
        name=variable_name,
        initial_value=some_result, # You determine this...
        logger=logger
    ),
     overwrite_existing=True
)
```
