### ISSUE TITLE
AwsBoto3CloudFormationTemplateParameters extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#6]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript") 

AwsBoto3CloudFormationTemplateParameters

## Brief description of functionality to be provided 

Defines a parameter to be passed into a CloudFormation template

## Issue Dependencies

If there are any other issues that should be implemented first, list them here

* None

# More detailed functional requirements

Different parameter values can be defined per account. Something like:

```yaml
metadata:
  name: some-parameter-name
spec:
  parameters:
  - parameterName: string
    parameterValue: string
```

In `AwsBoto3CloudFormationTemplate` parameters are used like such:

```yaml
spec:
  parameterReferences: # optional - reference one or more "AwsBoto3CloudFormationTemplateParameters" manifests
  - string # Reference to the name of a "AwsBoto3CloudFormationTemplateParameters" manifest
```

he data will be stored in the following `Variable` objects:

* PARAMETER_KEYS - A list of keys
* PARAMETERS - A dictionary in the format { "<<parameter_key>>": "<<parameter_value>>" }. All `parameter_value` values will be strings

References 

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
