### ISSUE TITLE
LocalFile extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#7]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript") 

LocalFile

## Brief description of functionality to be provided 

Points to a local file on the file system

## Issue Dependencies

If there are any other issues that should be implemented first, list them here

* None

# More detailed functional requirements

Basic spec:

```yaml
spec:
  directory: string
  filename: string
  touchIfNotExists: true # creates an empty file if the file does not exist
  loadContent: false # If true, loads the file content
```

Creates the following variables:

* `<<name>>:exists` - boolean
* `<<name>>:size` - int - size in bytes
* `<<name>>:sha256` - string with checksum
* `<<name>>:content` - bytes - default `b''` but otherwise if `loadContent` is true, will contain the file content (for files up to 10MiB)
