### ISSUE TITLE
WebDownloadFile extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#8]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript") 

WebDownloadFile

## Brief description of functionality to be provided 

Download a file from the Internet using HTTP(S) and save the content to a local file.

## Issue Dependencies

If there are any other issues that should be implemented first, list them here

* None

# More detailed functional requirements

Supported features required:

* HTTP basic authentication
* Custom headers, which may be useful for something like including bearer tokens
* Proxy configuration if required
* GET and other methods that do not require a body (content)
* POST and other methods that require a body (content)

Based on these, a full spec may look something like:

```yaml
spec:
  sourceUrl: string # Must start with "http" or "https"
  targetOutputFile: string
  skipSslVerification: false # optional, boolean, default=false
  proxy:
    host: string # (optional|default=None) - Must start with "http" or "https"
    basicAuthentication: # Optional, default=None
      username: string
      passwordVariableName: string # Contains the variable name, depending on source manifest implementation, that will contain the password
  extraHeaders: # (optional|default=[])
  - name: string
    value: string
  method: string # GET|POST|... (default=GET)
  body: string # (optional|default=None)
  httpBasicAuthentication: # Optional, default=None
    username: string
    passwordVariableName: string # Contains the variable name, depending on source manifest implementation, that will contain the password
```
