### ISSUE TITLE
GitRepo extension

### ISSUE THREAD

**Issue by nicc777** [nicc777/py-animus-extensions#9]
# Extension Metadata

Complete the following information:

## `Kind` name (e.g. "ShellScript") 

GitRepo

## Brief description of functionality to be provided 

Defines a Git repository and credentials required to clone it.

## Issue Dependencies

None

# More detailed functional requirements

The idea is to clone the repository into a local work directory and checkout the default branch.

The following spec may be a good start:

```yaml
spec:
  cloneUrl: string
  authentication: # Optional, default=None
    type: string # Either http or ssh
    httpAuthentication: # Required if type==http
      username: string
      password: string # Never put the actual password. See https://github.com/nicc777/py-animus/blob/main/doc/placeholder_values.md and https://github.com/nicc777/py-animus/blob/main/doc/placeholder_values.md#variables-and-manifest-dependencies
    sshAuthentication: # only used when type==ssh-private-key  
      sshPrivateKeyFile: string # The full path to the SSH private key
  workDir: string # Optional, default will be a random temporary directory
  checkoutBranch: string # optional, default="main"
  options:
    skipSslVerify: false # Only used for HTTPS. Default is false
```

Variables that will be set:

* `GIT_DIR` - Path to the working directory
* `BRANCH` - The branch checked out
